[package]
name = "pulse-tui"
version = "0.1.0"
edition = "2024"
description = "Try the Pulse API from your terminal"
license = "MIT"
repository = "https://github.com/isaac-shiga/pulse-tui"

[dependencies]
base64 = "0.23.1"
chrono = "0.4.45"
ratatui = { version = "0.30", features = ["unstable-rendered-line-info"] }
reqwest = { version = "0.13", features = ["blocking", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
throbber-widgets-tui = "0.11"
tui-input = "0.15"
uuid = { version = "1.27.0", features = ["v4"] }
